import Link from "next/link";
import type { Metadata } from "next";
import type { ReactNode } from "react";
export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html>
      <body>
        <nav style={{ padding: "10px", background: "#eee" }}>
          <Link href="/">Home</Link> |{" "}
          <Link href="/about">About</Link> |{" "}
          <Link href="/contact">Contact</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
